# Generated by Django 6.0.5 on 2026-07-16 08:20

import agent_api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0007_serviceportfolioitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('endpoint', models.CharField(max_length=100)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KBArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable topic key the model selects from.', unique=True)),
                ('title', models.CharField(max_length=200)),
                ('answer', models.TextField(help_text='Served verbatim. The model never rewrites this.')),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KB article',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SitemapDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('path', models.CharField(help_text='Site-relative path, e.g. /pricing.', max_length=300)),
                ('label', models.CharField(max_length=120)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AgentQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(default=agent_api.models._quote_id, editable=False, max_length=32, unique=True)),
                ('params', models.JSONField(default=dict)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('breakdown', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_quotes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_quotes', to='services.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_quotes', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Expose this service to Mica. Inactive services are hidden from the agent catalog.')),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Natural-language aliases, e.g. ["landing page", "website"].')),
                ('form', models.JSONField(blank=True, default=dict, help_text='Requirement form schema {title, fields:[…]}. Leave empty for a generic brief field.')),
                ('pricing_rules', models.JSONField(blank=True, default=dict, help_text='Deterministic pricing rules {base, base_label, rules:[…]}. Leave empty to price from the cheapest fixed PricingPlan.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_config', to='services.service')),
            ],
            options={
                'verbose_name': 'Agent service config',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('order', 'Order'), ('billing', 'Billing'), ('technical', 'Technical'), ('general', 'General'), ('other', 'Other')], default='general', max_length=20)),
                ('reason', models.CharField(choices=[('agent_handoff', 'Agent hand-off'), ('verify_exhausted', 'Verify exhausted')], default='agent_handoff', max_length=20)),
                ('customer_ref', models.CharField(blank=True, help_text='Email/handle Mica passed for anonymous or reference use.', max_length=254)),
                ('session_ref', models.CharField(blank=True, max_length=64)),
                ('transcript', models.JSONField(blank=True, default=list, help_text='Server-authored by Mica from her Message log — trusted evidence.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
