# Generated by Django 6.0.5 on 2026-07-16 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0002_seed_kb_sitemap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentquote',
            name='session_ref',
            field=models.CharField(blank=True, db_index=True, help_text='Mica conversation this quote belongs to (links it in the dashboard).', max_length=64),
        ),
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_ref', models.CharField(max_length=64, unique=True)),
                ('customer_ref', models.CharField(blank=True, help_text='Email/handle for an anonymous visitor (no account yet).', max_length=254)),
                ('channel', models.CharField(default='web_widget', max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('escalated', 'Escalated')], default='active', max_length=20)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_ref', models.CharField(blank=True, db_index=True, max_length=64)),
                ('kind', models.CharField(help_text='e.g. tool_call, tool_result, navigate, quote, order, ticket, verify, escalation, error.', max_length=40)),
                ('name', models.CharField(blank=True, help_text='Tool/action name.', max_length=120)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('ok', models.BooleanField(blank=True, help_text='Outcome for verify/action steps: passed (true) or failed (false).', null=True)),
                ('at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agent_api.agentconversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Customer'), ('agent', 'Mica'), ('system', 'System'), ('tool', 'Tool')], max_length=10)),
                ('text', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('client_id', models.CharField(blank=True, help_text='Optional Mica-side id used to de-duplicate re-sent messages.', max_length=64)),
                ('at', models.DateTimeField(blank=True, help_text="When the turn happened on Mica's side.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent_api.agentconversation')),
            ],
            options={
                'ordering': ['at', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_id__gt', '')), fields=('conversation', 'client_id'), name='uniq_message_client_id_per_conversation')],
            },
        ),
    ]
