# Generated by Django 6.0.5 on 2026-06-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('budget_range', models.CharField(choices=[('not_sure', 'Not sure yet'), ('under_50k', 'Under KES 50,000'), ('50k_200k', 'KES 50,000 – 200,000'), ('200k_500k', 'KES 200,000 – 500,000'), ('500k_1m', 'KES 500,000 – 1,000,000'), ('over_1m', 'Over KES 1,000,000')], default='not_sure', max_length=20)),
                ('timeline', models.CharField(choices=[('flexible', 'Flexible / Not sure'), ('asap', 'ASAP (within 2 weeks)'), ('1_month', 'Within 1 month'), ('1_3_months', '1 – 3 months'), ('3_6_months', '3 – 6 months'), ('6_plus', '6+ months')], default='flexible', max_length=20)),
                ('brief', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Staff-only notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'ordering': ['-created_at'],
            },
        ),
    ]
