# Generated by Django 6.0.5 on 2026-07-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='description',
            field=models.TextField(blank=True, help_text='Short summary shown under the tier name on the pricing card.'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='tier',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], help_text='Set for services in a tier-based category. Leave blank for custom plans.', max_length=20),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_tiered',
            field=models.BooleanField(default=False, help_text='Services in this category are sold as Basic / Standard / Premium tiers.'),
        ),
    ]
