# Generated by Django 6.0.5 on 2026-07-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_pricingplan_description_pricingplan_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_tiered',
            field=models.BooleanField(default=False, help_text='Sell this service as Basic / Standard / Premium tiers (also enabled automatically for tier-based categories).'),
        ),
    ]
