# Generated by Django 6.0.5 on 2026-07-05 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_is_tiered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')])),
                ('comment', models.TextField(help_text="The customer's review text.")),
                ('author_name', models.CharField(blank=True, help_text="Name shown publicly. Defaults to the customer's name.", max_length=100)),
                ('author_role', models.CharField(blank=True, help_text="e.g. 'CTO', 'Operations Lead'", max_length=150)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('is_approved', models.BooleanField(default=False, help_text='Approved reviews appear publicly in the Testimonials section.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='services.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
