# Generated by Django 6.0.5 on 2026-07-13 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(help_text='One or two sentences on what was built and the result.', max_length=400)),
                ('image', models.ImageField(blank=True, help_text='Upload a cover image (PNG, JPG, SVG, or WebP).', null=True, upload_to='service_portfolio/')),
                ('image_url', models.URLField(blank=True, help_text='Alternative to uploading: paste a direct image URL.')),
                ('client', models.CharField(blank=True, help_text='Client / company name (optional).', max_length=150)),
                ('link_url', models.CharField(blank=True, help_text='Link to the live project or case study (optional).', max_length=500)),
                ('link_label', models.CharField(blank=True, default='View project', help_text='Text for the portfolio link.', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='services.service')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
