# Generated by Django 6.0.5 on 2026-06-15 13:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_receipt_deployment_receipt_repos'),
        ('services', '0003_quoterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField(default=django.utils.timezone.now)),
                ('connected_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gmail Credential',
            },
        ),
        migrations.CreateModel(
            name='GmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=30, unique=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('snippet', models.CharField(blank=True, max_length=500)),
                ('from_email', models.CharField(blank=True, max_length=300)),
                ('to_emails', models.JSONField(default=list)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('labels', models.JSONField(default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gmail_threads', to='contracts.client')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gmail_threads', to='services.order')),
            ],
            options={
                'verbose_name': 'Gmail Thread',
                'verbose_name_plural': 'Gmail Threads',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='GmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=30, unique=True)),
                ('from_email', models.CharField(blank=True, max_length=300)),
                ('to_emails', models.JSONField(default=list)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gmail.gmailthread')),
            ],
            options={
                'verbose_name': 'Gmail Message',
                'ordering': ['sent_at'],
            },
        ),
    ]
