# Generated by Django 6.0.5 on 2026-06-15 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github_repos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VercelProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vercel_project_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('framework', models.CharField(choices=[('nextjs', 'Next.js'), ('vite', 'Vite'), ('gatsby', 'Gatsby'), ('remix', 'Remix'), ('other', 'Other')], default='nextjs', max_length=20)),
                ('production_url', models.URLField(blank=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255)),
                ('team_id', models.CharField(blank=True, help_text='Vercel team ID (optional)', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vercel_projects', to='github_repos.githubrepo')),
            ],
            options={
                'verbose_name': 'Vercel Project',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vercel_deployment_id', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(blank=True)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('preview', 'Preview'), ('development', 'Development')], default='production', max_length=20)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('commit_sha', models.CharField(blank=True, max_length=40)),
                ('commit_message', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('building', 'Building'), ('ready', 'Ready'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_deployments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='deployments.vercelproject')),
            ],
            options={
                'verbose_name': 'Deployment',
                'ordering': ['-created_at'],
            },
        ),
    ]
