# Generated by Django 6.0.5 on 2026-06-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. "2026", "5+", "BN-93S95J2J"', max_length=50)),
                ('label', models.CharField(help_text='e.g. "Founded in Nairobi"', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About Metric',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(help_text='e.g. "rentflow", "platform", "tools"', max_length=50)),
                ('version', models.CharField(help_text='e.g. "v3.1"', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Short description of what changed.')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of {type: "new"|"imp"|"fix", text: "..."} objects.')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Changelog Entry',
                'verbose_name_plural': 'Changelog Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. "2.4M+"', max_length=50)),
                ('label', models.CharField(help_text='e.g. "Transactions reconciled"', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Stat',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('rails', 'Trust Strip (Rails)'), ('trusted_by', 'Logo Strip (Trusted By)')], default='trusted_by', max_length=20)),
                ('logo_svg', models.TextField(blank=True, help_text='Paste SVG path/rect/circle content only — no outer <svg> tag. ViewBox is "0 0 20 21". Example: <path d="M3 18V7l7-4 7 4v11"/>')),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable service name', max_length=100)),
                ('url', models.URLField(help_text='Endpoint to probe for health checks')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service Status',
                'verbose_name_plural': 'Service Statuses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_hero_template', models.CharField(choices=[('orbital', 'Orbital Diagram'), ('code', 'Code Window'), ('grid', '3D Grid'), ('minimal', 'Minimal Typography')], default='orbital', help_text='Which visual template to display in the hero art area.', max_length=20)),
                ('hero_eyebrow', models.CharField(default='Multi-product software studio · Est. 2024', max_length=200)),
                ('hero_headline', models.CharField(default='Infrastructure for the East African internet.', max_length=200)),
                ('hero_subheading', models.TextField(blank=True, default='We build the SaaS and developer tooling East African operators actually ship on. M-Pesa-native, Daraja-fluent, production-grade — and serious about it.')),
                ('hero_primary_cta_text', models.CharField(default='Explore products', max_length=100)),
                ('hero_primary_cta_url', models.CharField(default='#products', max_length=200)),
                ('hero_secondary_cta_text', models.CharField(default='Read the docs', max_length=100)),
                ('hero_secondary_cta_url', models.CharField(default='#tools', max_length=200)),
                ('trust_strip_label', models.CharField(default='Runs on the rails you already use', max_length=200)),
                ('logo_strip_label', models.CharField(default='Trusted by operators across East Africa', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('photo_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True)),
                ('product_label', models.CharField(blank=True, help_text='e.g. "RentFlow"', max_length=50)),
                ('product_accent_color', models.CharField(blank=True, default='#34D399', help_text='Hex color for the product badge', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
