# Generated by Django 6.0.5 on 2026-06-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier, e.g. "daraja-playground"', unique=True)),
                ('tagline', models.CharField(help_text='One-liner shown on the card', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Longer description shown on the tool page (Markdown supported)')),
                ('category', models.CharField(choices=[('mpesa', 'M-Pesa'), ('developer', 'Developer'), ('finance', 'Finance'), ('utilities', 'Utilities'), ('data', 'Data'), ('other', 'Other')], default='other', max_length=20)),
                ('icon_svg', models.TextField(blank=True, help_text='SVG path/shape content only — no outer <svg> tag. ViewBox is "0 0 24 24". Example: <path d="M7 8l4 4-4 4M13 16h4"/>')),
                ('accent_color', models.CharField(blank=True, default='#22D3EE', help_text='Hex color for the icon glow and card accent', max_length=20)),
                ('cta_label', models.CharField(blank=True, default='Open tool', help_text='Button label, e.g. "Open tool", "Try it free"', max_length=60)),
                ('cta_url', models.CharField(blank=True, help_text='Where the CTA button points. Leave blank if not yet live.', max_length=500)),
                ('is_free', models.BooleanField(default=True)),
                ('is_coming_soon', models.BooleanField(default=False, help_text='Grays out the card and replaces the CTA with "Coming soon"')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
