# Generated by Django 6.0.5 on 2026-06-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='logo_svg',
        ),
        migrations.AddField(
            model_name='partner',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Upload a PNG, JPG, SVG, or WebP logo file.', null=True, upload_to='partners/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Alternative to uploading: paste a direct URL to the logo image.'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website_url',
            field=models.URLField(blank=True, help_text="Link to the partner's website (optional)."),
        ),
    ]
