# Generated by Django 6.0.5 on 2026-06-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_contactinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_founder',
            field=models.BooleanField(default=False, help_text='Check for founders / co-founders'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_primary_cta_url',
            field=models.CharField(default='#services', max_length=200),
        ),
    ]
