# Generated by Django 6.0.5 on 2026-06-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_teammember_is_founder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='founder_message',
            field=models.TextField(blank=True, help_text='Personal statement shown in the "From our founders" section on the About page.'),
        ),
    ]
