# Generated by Django 6.0.5 on 2026-06-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_teammember_founder_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestatus',
            name='consecutive_fails',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text='Number of consecutive failed probes'),
        ),
        migrations.AddField(
            model_name='servicestatus',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='servicestatus',
            name='last_response_ms',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='servicestatus',
            name='last_status',
            field=models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', editable=False, max_length=20),
        ),
    ]
