# Generated by Django 6.0.5 on 2026-06-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_servicestatus_consecutive_fails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier, e.g. "rentflow-rebuild"', unique=True)),
                ('client', models.CharField(blank=True, help_text='Client / company name (optional)', max_length=150)),
                ('category', models.CharField(choices=[('product', 'Product Build'), ('web', 'Website / Web App'), ('mobile', 'Mobile App'), ('integration', 'API & Integration'), ('tooling', 'Developer Tooling'), ('branding', 'Design & Branding'), ('other', 'Other')], default='product', max_length=20)),
                ('summary', models.CharField(help_text='One-liner shown on the card', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Longer write-up shown on the project page (Markdown supported)')),
                ('cover_image', models.ImageField(blank=True, help_text='Upload a cover image (PNG, JPG, SVG, or WebP).', null=True, upload_to='projects/')),
                ('cover_url', models.URLField(blank=True, help_text='Alternative to uploading: paste a direct URL to the cover image.')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of strings shown as chips, e.g. ["Next.js", "Django", "M-Pesa"].')),
                ('accent_color', models.CharField(blank=True, default='#22D3EE', help_text='Hex color for the card accent', max_length=20)),
                ('live_url', models.URLField(blank=True, help_text='Live site / product URL (optional)')),
                ('result_metric', models.CharField(blank=True, help_text='Headline outcome, e.g. "2.4M transactions reconciled" (optional)', max_length=120)),
                ('year', models.CharField(blank=True, help_text='e.g. "2025"', max_length=10)),
                ('completed_at', models.DateField(blank=True, help_text='Completion date — newest shown first', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in the homepage "Recent work" teaser')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-completed_at', '-created_at'],
            },
        ),
    ]
