# Generated by Django 6.0.5 on 2026-07-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_sitesettings_active_hero_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='active_hero_template',
            field=models.CharField(choices=[('orbital', 'Orbital Diagram'), ('code', 'Code Window'), ('grid', '3D Grid'), ('minimal', 'Minimal Typography'), ('aurora', 'Platform Stack (layered)'), ('bento', 'Capability Bento (what we build)')], default='orbital', help_text='Which visual template to display in the hero art area.', max_length=20),
        ),
    ]
