# Generated by Django 6.0.5 on 2026-07-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_sitesettings_active_hero_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(help_text='Small label under the name, e.g. "SaaS · PropTech"', max_length=100)),
                ('status', models.CharField(choices=[('live', 'Live'), ('beta', 'Beta'), ('soon', 'Coming soon')], default='soon', help_text='Drives the badge (LIVE / BETA / COMING SOON) and card styling.', max_length=10)),
                ('description', models.TextField(help_text='Short paragraph shown on the card.')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of short strings shown as ticked bullets, e.g. ["Auto-reconciliation", "Tenant ledgers"].')),
                ('icon_path', models.TextField(blank=True, help_text='SVG path data only — the value of a single <path d="…"> on a "0 0 24 24" viewBox. Example: M3 21h18M6 21V5a2 2 0 012-2h8a2 2 0 012 2v16')),
                ('accent_color', models.CharField(blank=True, default='#34D399', help_text='Hex color for the card accent and icon glow.', max_length=20)),
                ('link_url', models.CharField(blank=True, help_text='Where the card links to, e.g. "/rentflow" or "/contact". Ignored while status is "Coming soon".', max_length=500)),
                ('cta_label', models.CharField(blank=True, default='View product', help_text='Card link label, e.g. "View product", "Request access".', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
