# Generated by Django 6.0.5 on 2026-07-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_seed_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(help_text='One-liner shown under the name.', max_length=200)),
                ('accent_color', models.CharField(blank=True, default='#22D3EE', help_text='Hex color for the card accent border.', max_length=20)),
                ('is_available', models.BooleanField(default=False, help_text='Checked = "Available" badge; unchecked = "Coming soon".')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Developer Integration',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
