# Generated by Django 6.0.5 on 2026-06-15 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('user', 'Personal'), ('org', 'Organisation')], default='user', max_length=10)),
                ('avatar_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'GitHub Account',
                'verbose_name_plural': 'GitHub Accounts',
                'ordering': ['login'],
            },
        ),
        migrations.CreateModel(
            name='GitHubRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('html_url', models.URLField()),
                ('language', models.CharField(blank=True, max_length=60)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('topics', models.JSONField(default=list)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('project_label', models.CharField(blank=True, max_length=100)),
                ('internal_notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='github_repos.githubaccount')),
            ],
            options={
                'verbose_name': 'GitHub Repo',
                'verbose_name_plural': 'GitHub Repos',
                'ordering': ['-stars', 'name'],
            },
        ),
    ]
