# Generated by Django 6.0.5 on 2026-06-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_repos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
