# Generated by Django 6.0.5 on 2026-06-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_repos', '0002_githubaccount_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubaccount',
            name='access_token',
            field=models.TextField(blank=True),
        ),
    ]
