# Generated by Django 6.0.5 on 2026-06-12 18:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True, help_text='Billing address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('title', models.CharField(help_text='e.g. "Phase 1 — Product Development"', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Optional project description shown on the receipt')),
                ('line_items', models.JSONField(blank=True, default=list, help_text='Array of line items. Format: [{"description": "Feature development", "qty": 1, "unit_price": 150000}, ...]')),
                ('currency', models.CharField(choices=[('KES', 'KES — Kenyan Shilling'), ('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound')], default='KES', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, help_text='VAT rate as a percentage (e.g. 16). Set to 0 to omit tax line.', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Shown at the bottom of the receipt')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('download_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='contracts.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
