# Generated by Django 6.0.5 on 2026-06-15 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('deployments', '0001_initial'),
        ('github_repos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='deployment',
            field=models.ForeignKey(blank=True, help_text='Primary Vercel project for this receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='deployments.vercelproject'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='repos',
            field=models.ManyToManyField(blank=True, help_text='GitHub repos associated with this project', related_name='receipts', to='github_repos.githubrepo'),
        ),
    ]
